export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';

export const SAVE_POST_IN_STORE = 'SAVE_POST_IN_STORE';
export const RESET_POST_CREATION = 'RESET_POST_CREATION';

export const DELETE_POST = 'DELETE_POST';
